name: Backend CD

on:
  pull_request:
    paths:
      - '.github/workflows/backend-cd.yaml'
      - '**/backend/**'
    branches:
      - 'main'
  push:
    paths:
      - '.github/workflows/backend-cd.yaml'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./starter/backend

permissions:
  contents: read

jobs:
  backend-ci:
    uses: ./.github/workflows/backend-ci.yaml
    name: Backend CI - Lint, Test & Build

  push-to-ecr:
    name: Backend CD
    needs: backend-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build  -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
