name: Frontend CI

on:
  pull_request:
    paths:
      - '**/frontend/**'
    branches:
      - 'main'
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash
    working-directory: ./starter/frontend

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test
        run: npm run build

      - name: Build docker image
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=${{ vars.REACT_APP_MOVIE_API_URL }} --tag=mp-frontend:latest .
