name: Frontend CD

on:
  push:
    paths:
      - '**/frontend/**'
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    # working-directory: ./starter/frontend

jobs:
  lint-test-build:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Frontend CI
        uses: ./.github/workflows/frontend-ci.yaml

  push-to-ecr:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-access-key-id:
          aws-secret-access-key:
          aws-region: aws-region-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
